apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mychart
spec:
  project: default
  destination:
    namespace: rob-2
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: 'https://nutrienrob.github.io/argocd-example-apps'
    chart: 'mychart'
    targetRevision: '0.1.0'
    helm:
      values: |
        favoriteDrink: tea
        mysubschart:
          dessert: chocolate ice cream
