apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mychart
spec:
  project: default
  destination:
    namespace: rob-2
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/nutrienrob/argocd-example-apps.git
    path: mychart
    targetRevision: HEAD
    helm:
      values: |
        favoriteDrink: tea
        mysubschart:
          dessert: chocolate ice cream
